import { NextResponse } from 'next/server'

const MOCK_QUESTION_REPORTS = [
  {
    question: {
      question_id: 'q-1', set_id: 'set-1', type: 'multiple_choice', order_index: 1,
      content: '다음 중 집합의 원소가 될 수 없는 것은?',
      options: [
        { index: 1, text: '자연수 전체의 집합' },
        { index: 2, text: '1보다 작은 자연수' },
        { index: 3, text: '짝수인 소수' },
        { index: 4, text: '키가 170cm인 사람' },
      ],
      answer: '4', hint: null, explanation: null, media_url: null,
      learning_map: { depth1: '수와 연산' },
      difficulty: '보통',
      created_at: '2026-01-10T09:00:00Z',
    },
    total_participants: 15,
    correct_count: 11,
    correct_rate: 0.73,
    avg_response_time_sec: 8.3,
    min_response_time_sec: 3.1,
    max_response_time_sec: 18.7,
    distribution: { '1': 1, '2': 2, '3': 1, '4': 11 },
  },
  {
    question: {
      question_id: 'q-2', set_id: 'set-1', type: 'ox', order_index: 2,
      content: '공집합은 모든 집합의 부분집합이다.',
      options: null, answer: 'O', hint: null, explanation: null, media_url: null,
      learning_map: { depth1: '수와 연산' },
      difficulty: '쉬움',
      created_at: '2026-01-10T09:00:00Z',
    },
    total_participants: 15,
    correct_count: 14,
    correct_rate: 0.93,
    avg_response_time_sec: 5.1,
    min_response_time_sec: 1.2,
    max_response_time_sec: 12.0,
    distribution: { 'O': 14, 'X': 1 },
  },
  {
    question: {
      question_id: 'q-3', set_id: 'set-1', type: 'multiple_choice', order_index: 3,
      content: 'A = {1,2,3}, B = {2,3,4} 일 때, A∩B는?',
      options: [
        { index: 1, text: '{1,2,3,4}' },
        { index: 2, text: '{2,3}' },
        { index: 3, text: '{1,4}' },
        { index: 4, text: '{}' },
      ],
      answer: '2', hint: null, explanation: null, media_url: null,
      learning_map: { depth1: '집합과 명제' },
      difficulty: '보통',
      created_at: '2026-01-10T09:00:00Z',
    },
    total_participants: 15,
    correct_count: 9,
    correct_rate: 0.60,
    avg_response_time_sec: 11.2,
    min_response_time_sec: 4.5,
    max_response_time_sec: 20.0,
    distribution: { '1': 4, '2': 9, '3': 1, '4': 1 },
  },
  {
    question: {
      question_id: 'q-4', set_id: 'set-1', type: 'multiple_choice', order_index: 4,
      content: '{x | x는 10 이하의 소수}의 원소 개수는?',
      options: [
        { index: 1, text: '3개' },
        { index: 2, text: '4개' },
        { index: 3, text: '5개' },
        { index: 4, text: '6개' },
      ],
      answer: '2', hint: null, explanation: null, media_url: null,
      learning_map: { depth1: '수와 연산', depth2: '소수' },
      difficulty: '어려움',
      created_at: '2026-01-10T09:00:00Z',
    },
    total_participants: 15,
    correct_count: 7,
    correct_rate: 0.47,
    avg_response_time_sec: 18.5,
    min_response_time_sec: 5.0,
    max_response_time_sec: 20.0,
    distribution: { '1': 3, '2': 7, '3': 4, '4': 1 },
  },
  {
    question: {
      question_id: 'q-5', set_id: 'set-1', type: 'ox', order_index: 5,
      content: '집합 A = {1, 2, 3}의 부분집합의 개수는 8개이다.',
      options: null, answer: 'O', hint: null, explanation: null, media_url: null,
      learning_map: { depth1: '집합과 명제' },
      difficulty: '보통',
      created_at: '2026-01-10T09:00:00Z',
    },
    total_participants: 15,
    correct_count: 5,
    correct_rate: 0.33,
    avg_response_time_sec: 14.0,
    min_response_time_sec: 3.0,
    max_response_time_sec: 20.0,
    distribution: { 'O': 5, 'X': 10 },
  },
]

export async function GET() {
  return NextResponse.json(MOCK_QUESTION_REPORTS)
}
